# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Template-Plugin-Stash
version:      1.006
version_from: lib/Template/Plugin/Stash.pm
installdirs:  site
requires:
    Template::Plugin:              0
    Test::Simple:                  0.44

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.21
